package utils

var translations []Translation

func GetTranslations() *[]Translation {
	return &translations
}

func GetTranslation(name string) Translation {
	var ret Translation
	for _, x := range translations {
		if x.ActionName == name {
			ret = x
		}
	}
	return ret
}
func GetTranslationsByLanguage(language string) []Translation {

	var ret []Translation
	for _, x := range translations {
		if x.Language == language {
			ret = append(ret, x)
		}
	}
	return ret
}

func SetBaseValueTranslations() {

	//EVENTS

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Money",
		ShortName:   "Money",
		LongName:    "Amount of money",
		Description: "How much money you have. You can spend money on actions and money is used to pay your army upkeep. if you fall below 0, you'll be unable to produce anything.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbSoldier",
		ShortName:   "Soldiers",
		LongName:    "Number of soldiers",
		Description: "How many soldier are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbLigtTank",
		ShortName:   "Light tanks",
		LongName:    "Number of light tanks",
		Description: "How many light tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbHvyTank",
		ShortName:   "Heavy tanks",
		LongName:    "Number of heavy tanks",
		Description: "How many heavy tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbArt",
		ShortName:   "Artillery",
		LongName:    "Number of artillery",
		Description: "How many artillery are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirSup",
		ShortName:   "Fighter aircraft",
		LongName:    "Number of fighter aircraft",
		Description: "How many fighter aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "InfantryEquipment",
		ShortName:   "Infantry equipment",
		LongName:    "Number of Infantry equipment in reserve",
		Description: "Infantry equipment are used to train new soldier in your barracks",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Ammunition",
		ShortName:   "Ammunition",
		LongName:    "Ammunition reserve",
		Description: "How many Ammunition do you have in stock. When you're running out of ammunition, you lose 1% quality per turn.",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbResearchPoint",
		ShortName:   "Research points",
		LongName:    "Research points",
		Description: "Your research point are generated by your scientists, and used to unlock new technologies",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbScientist",
		ShortName:   "Scientists",
		LongName:    "Scientists",
		Description: "Scientists generate research point, and used to unlock new technologies. be careful, your enemy can send some spy to kill them !",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "SmallCities",
		ShortName:   "Small cities",
		LongName:    "Small cities",
		Description: "Small cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "BigCities",
		ShortName:   "Big cities",
		LongName:    "Big cities",
		Description: "Big cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "MediumCities",
		ShortName:   "Medium cities",
		LongName:    "Medium cities",
		Description: "Medium cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Barracks",
		ShortName:   "Barracks",
		LongName:    "Barracks",
		Description: "Barracks determine how much you can train soldier each turn.",
	})

	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial1",
		ShortName:  "Welcome ! This is a duel strategy game. You're leading a country into a war. But you're not really the warmongering type. You prefer the comfy situation of na excel spreadsheet than the smell of firearms and dead bodies.",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial2",
		ShortName:  "Quick tutorial : The goal is to capture the whole enemy territory, which is represented by cities of various size. Each turn, both armies are inflicting damage to the other one, and if there's one which inflicts significantly more damage than the other, the winning army capture 1% of the losing side territory, and can take some cities and barracks.",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial3",
		ShortName:  "To help your army, you have to manage your production, research technologies, use your money to take some radical actions. Be careful, the enemy will also do this and will try to overrun you",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial4",
		ShortName:  "",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial5",
		ShortName:  "",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "InfosTooltip",
		Description: "This is your informations. This is a quick recap of all the most important informations about your current situation. The value in green are your production each turn. It don't take your loss in account.",
	})

	//TECHNOLOGY
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production",
		Description: "Boost civilian factory production by 15%",
		ActionName:  "technoIndusT1N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production T2",
		Description: "Boost civilian factory production by 15%",
		ActionName:  "technoIndusT2N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production T3",
		Description: "Boost civilian factory production by 25%",
		ActionName:  "technoIndusT3N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production T2",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT2N2",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production T3",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT3N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Aircraft production",
		Description: "Boost Aircraft factory production by 15%",
		ActionName:  "technoIndusT1N3",
	})

	//MIL TECHNOLOGY

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 10%",
		ActionName:  "technoMilT1N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 15%",
		ActionName:  "technoMilT2N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 20%",
		ActionName:  "technoMilT3N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 10%",
		ActionName:  "technoMilT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 15%",
		ActionName:  "technoMilT2N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 20%",
		ActionName:  "technoMilT3N2",
	})

	//ECO
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Administration Reform - Tax",
		Description: "Reform tax administration to ensure you gather tax more efficiently",
		ActionName:  "technoEcoT1N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Administration Reform - Reasearch",
		Description: "Reform Reasearch administration to ensure your scientist work in better conditions",
		ActionName:  "technoEcoT2N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Intelligence deployment",
		Description: "Unlock some intelligence action, like more effective sabotage",
		ActionName:  "technoEcoT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Advanced intelligence deployment",
		Description: "Unlock some intelligence action, like more effective sabotage and assasination",
		ActionName:  "technoEcoT2N2",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Financial devlopment",
		Description: "Unlock some financial action, like larger loans",
		ActionName:  "technoEcoT1N3",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Advanced Financial devlopment",
		Description: "Unlock some financial action, like larger loans",
		ActionName:  "technoEcoT2N3",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Add ? morale <img class='icon' src='morale.png' />",
		Description: "Add ? morale <img class='icon' src='morale.png' />, which then decay to get back to 100. Morale is an overall boost to damage and help prevent loss.",
		ActionName:  "addMorale",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Add ? quality <img class='icon' src='quality.png' />",
		Description: "Add ? quality <img class='icon' src='quality.png' /> .Quality is an overall boost to damage and help prevent loss. unlike Morale, Quality doesn't decay over time.",
		ActionName:  "addQuality",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Sacrifice ?% of your soldiers",
		Description: "Sometimes, victory need sacrifice.",
		ActionName:  "sacrificeSoldier",
	})

}
