package utils

var translations []Translation

func GetTranslations() *[]Translation {
	return &translations
}

func GetTranslation(name string) Translation {
	var ret Translation
	for _, x := range translations {
		if x.ActionName == name {
			ret = x
		}
	}
	return ret
}
func GetTranslationsByLanguage(language string) []Translation {

	var ret []Translation
	for _, x := range translations {
		if x.Language == language {
			ret = append(ret, x)
		}
	}
	return ret
}

func SetBaseValueTranslations() {

	//EVENTS

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbSoldier",
		ShortName:   "Soldiers",
		LongName:    "Number of soldiers",
		Description: "How many soldier are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbLigtTank",
		ShortName:   "Light tanks",
		LongName:    "Number of light tanks",
		Description: "How many light tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbHvyTank",
		ShortName:   "Heavy tanks",
		LongName:    "Number of heavy tanks",
		Description: "How many heavy tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbArt",
		ShortName:   "Artillery",
		LongName:    "Number of artillery",
		Description: "How many artillery are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirSup",
		ShortName:   "Fighter aircraft",
		LongName:    "Number of fighter aircraft",
		Description: "How many fighter aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "InfantryEquipment",
		ShortName:   "Infantry equipment",
		LongName:    "Number of Infantry equipment in reserve",
		Description: "Infantry equipment are used to train new soldier in your barracks",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Ammunition",
		ShortName:   "Ammunition",
		LongName:    "Ammunition reserve",
		Description: "How many Ammunition do you have in stock. When you're running out of ammunition, you lose 1% quality per turn.",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbResearchPoint",
		ShortName:   "Research points",
		LongName:    "Research points",
		Description: "Your research point are generated by your scientists, and used to unlock new technologies",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbScientist",
		ShortName:   "Scientists",
		LongName:    "Scientists",
		Description: "Scientists generate research point, and used to unlock new technologies. be careful, your enemy can send some spy to kill them !",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "SmallCities",
		ShortName:   "Small cities",
		LongName:    "Small cities",
		Description: "Small cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "BigCities",
		ShortName:   "Big cities",
		LongName:    "Big cities",
		Description: "Big cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "MediumCities",
		ShortName:   "Medium cities",
		LongName:    "Medium cities",
		Description: "Medium cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Barracks",
		ShortName:   "Barracks",
		LongName:    "Barracks",
		Description: "Barracks determine how much you can train soldier each turn.",
	})

}
