package utils

var translations []Translation

func GetTranslations() *[]Translation {
	return &translations
}

func GetTranslation(name string) Translation {
	var ret Translation
	for _, x := range translations {
		if x.ActionName == name {
			ret = x
		}
	}
	return ret
}
func GetTranslationsByLanguage(language string) []Translation {

	var ret []Translation
	for _, x := range translations {
		if x.Language == language {
			ret = append(ret, x)
		}
	}
	return ret
}

func SetBaseValueTranslations() {

	//EVENTS

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Money",
		ShortName:   "Money",
		LongName:    "Amount of money",
		Description: "How much money you have. You can spend money on actions and money is used to pay your army upkeep. if you fall below 0, you'll be unable to produce anything.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbSoldier",
		ShortName:   "Soldiers",
		LongName:    "Number of soldiers",
		Description: "How many soldier are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbLigtTank",
		ShortName:   "Light tanks",
		LongName:    "Number of light tanks",
		Description: "How many light tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbHvyTank",
		ShortName:   "Heavy tanks",
		LongName:    "Number of heavy tanks",
		Description: "How many heavy tanks are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbArt",
		ShortName:   "Artillery",
		LongName:    "Number of artillery",
		Description: "How many artillery are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirSup",
		ShortName:   "Fighter aircraft",
		LongName:    "Number of fighter aircraft",
		Description: "How many fighter aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbAirBomb",
		ShortName:   "Bomber aircraft",
		LongName:    "Number of bomber aircraft",
		Description: "How many bomber aircraft are fighting for you",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "InfantryEquipment",
		ShortName:   "Infantry equipment",
		LongName:    "Number of Infantry equipment in reserve",
		Description: "Infantry equipment are used to train new soldier in your barracks",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Ammunition",
		ShortName:   "Ammunition",
		LongName:    "Ammunition reserve",
		Description: "How many Ammunition do you have in stock. When you're running out of ammunition, you lose 1% quality per turn.",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbResearchPoint",
		ShortName:   "Research points",
		LongName:    "Research points",
		Description: "Your research point are generated by your scientists, and used to unlock new technologies",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "NbScientist",
		ShortName:   "Scientists",
		LongName:    "Scientists",
		Description: "Scientists generate research point, and used to unlock new technologies. be careful, your enemy can send some spy to kill them !",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "SmallCities",
		ShortName:   "Small cities",
		LongName:    "Small cities",
		Description: "Small cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "BigCities",
		ShortName:   "Big cities",
		LongName:    "Big cities",
		Description: "Big cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "MediumCities",
		ShortName:   "Medium cities",
		LongName:    "Medium cities",
		Description: "Medium cities inside your territory. Each city generate income each turn, based on their size. Caputre enemy territory to won new cities !",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Barracks",
		ShortName:   "Barracks",
		LongName:    "Barracks",
		Description: "Barracks determine how much you can train soldier each turn.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Factory",
		ShortName:   "Factories",
		LongName:    "Factories",
		Description: "Factories produce war material. You can change the production repartition in your industrial tab.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Morale",
		ShortName:   "Morale",
		LongName:    "Morale",
		Description: "Morale is an overall boost to damage and help prevent loss. Morale decay over time.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Quality",
		ShortName:   "Quality",
		LongName:    "Quality",
		Description: "Quality is an overall boost to damage and help prevent loss. unlike Morale, Quality doesn't decay over time.",
	})

	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial1",
		ShortName:  "Welcome ! This is a duel strategy game. You're leading a country into a war. But you're not really the warmongering type. You prefer the comfy situation of na excel spreadsheet than the smell of firearms and dead bodies.",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial2",
		ShortName:  "Quick tutorial : The goal is to capture the whole enemy territory, which is represented by cities of various size. Each turn, both armies are inflicting damage to the other one, and if there's one which inflicts significantly more damage than the other, the winning army capture 1% of the losing side territory, and can take some cities and barracks.",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial3",
		ShortName:  "To help your army, you have to manage your production, research technologies, use your money to take some radical actions. Be careful, the enemy will also do this and will try to overrun you",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial4",
		ShortName:  "",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "HomeTutorial5",
		ShortName:  "",
	})

	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "BasicTutorial1",
		ShortName:  "War progress : This is the visual representation of the war progress. The left part is your own territory, the right part is the enemy territory. The numbers in those part are the total damage you inflicts to the enemy ground army (after mitigation and all modifiers). When a side inflict significantly more damage, he can progress and capture a little part of country. The winning side is showed by little arrows. ",
	})
	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "BasicTutorial2",
		ShortName:  "Actions : This is the part of the interface where you take decision, change your policies, and push buttons. Actions are split by categories ans sub categories. Each action will have a cost, some constraints and some effects. If you can't satisfy the cost or the constrints, the action will be greyed. You can have more detail about what button will do by over your mouse on them. If some button are locked behind a technology, it will be showed which on you lack.",
	})

	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "BasicTutorial3",
		ShortName:  "Events : During the game, there will be some random events. Some are positive, some are a serious malus. Here you can have a quick view about what event happened to you. If you over them, you'll have a quick description of their effects.",
	})

	translations = append(translations, Translation{
		Language:   "en",
		ActionName: "BasicTutorial4",
		ShortName:  "Technologies : Here you can unlock some technologies, using your research points. Research points are generated by your scientists. Technologies can require you to already have other technologies unlocked, usually 1 tier below.",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "InfosTooltip",
		Description: "This is your informations. This is a quick recap of all the most important informations about your current situation. The value in green are your production each turn. It don't take your loss in account.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Tips1",
		Description: "Money is your main ressource. You will need it for most actions and your army will consume a large chunck of it. You earn money the tax applied on your cities. You can change the tax rate in the economy / tax part. Be careful, the more you tax, the less your factories will produce.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Tips2",
		Description: "Factories are the backbone of your production. They're located in the heart of your country, so even if you lose lot of terriory, you'll still be able to produce. You should be careful about enemy bomber, which can target and destroy your factories.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Tips3",
		Description: "Aircrafts, bombers and fighters, stay hidden in your airport by default. They are protected, but won't participate to the war effort. You can send them to the fight anytime in the section military/commandment.",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ActionName:  "Tips4",
		Description: "Morale is great to have a quick boost in combat to prevent losing territory or acute your advantage, but will fade quickly. Quality is more expansive, but will stay during all the war. Technologies are great because they don't cost money, but will only boost one side of your army / economy.  ",
	})

	//TECHNOLOGY
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production",
		Description: "Boost civilian factory production by 15%",
		ActionName:  "technoIndusT1N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production T2",
		Description: "Boost civilian factory production by 15%",
		ActionName:  "technoIndusT2N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Civilian production T3",
		Description: "Boost civilian factory production by 25%",
		ActionName:  "technoIndusT3N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production T2",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT2N2",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Tank production T3",
		Description: "Boost Tank factory production by 15%",
		ActionName:  "technoIndusT3N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost Aircraft production",
		Description: "Boost Aircraft factory production by 15%",
		ActionName:  "technoIndusT1N3",
	})

	//MIL TECHNOLOGY

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 10%",
		ActionName:  "technoMilT1N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 15%",
		ActionName:  "technoMilT2N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost soldier damage",
		Description: "Boost soldier damage by 20%",
		ActionName:  "technoMilT3N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 10%",
		ActionName:  "technoMilT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 15%",
		ActionName:  "technoMilT2N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Boost light tank damage",
		Description: "Boost light tank damage by 20%",
		ActionName:  "technoMilT3N2",
	})

	//ECO
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Administration Reform - Tax",
		Description: "Reform tax administration to ensure you gather tax more efficiently",
		ActionName:  "technoEcoT1N1",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Administration Reform - Reasearch",
		Description: "Reform Reasearch administration to ensure your scientist work in better conditions",
		ActionName:  "technoEcoT2N1",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Intelligence deployment",
		Description: "Unlock some intelligence action, like more effective sabotage",
		ActionName:  "technoEcoT1N2",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Advanced intelligence deployment",
		Description: "Unlock some intelligence action, like more effective sabotage and assasination",
		ActionName:  "technoEcoT2N2",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Financial devlopment",
		Description: "Unlock some financial action, like larger loans",
		ActionName:  "technoEcoT1N3",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Advanced Financial devlopment",
		Description: "Unlock some financial action, like larger loans",
		ActionName:  "technoEcoT2N3",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Add ? morale <img class='icon' src='morale.png' />",
		Description: "Add ? morale <img class='icon' src='morale.png' />, which then decay to get back to 100. Morale is an overall boost to damage and help prevent loss.",
		ActionName:  "addMorale",
	})

	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Add ? quality <img class='icon' src='quality.png' />",
		Description: "Add ? quality <img class='icon' src='quality.png' /> .Quality is an overall boost to damage and help prevent loss. unlike Morale, Quality doesn't decay over time.",
		ActionName:  "addQuality",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Add ? quality <img class='icon' src='quality.png' /> for heavy tank.",
		Description: "Add ? quality <img class='icon' src='quality.png' /> .Quality is an overall boost to damage and help prevent loss. unlike Morale, Quality doesn't decay over time.",
		ActionName:  "heavyTankQuality",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Sacrifice ?% of your soldiers",
		Description: "Sometimes, victory need sacrifice.",
		ActionName:  "sacrificeSoldier",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "You deal ?% more damage in aerial combat",
		Description: "Total air domination",
		ActionName:  "dmgAerialBonus",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Your bomber are ?% more effective",
		Description: "Rain of fire",
		ActionName:  "dmgBombBonus",
	})

	//Countries
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "Germany",
		Description: "Specialized in heavy tanks and high quality army.",
		ActionName:  "Germany",
	})
	translations = append(translations, Translation{
		Language:    "en",
		ShortName:   "France",
		Description: "Specialized in aircraft. Have some technology related to tax.",
		ActionName:  "France",
	})

}
